export declare const ssmClassifyStreetNamePieceOverrides: {
    readonly garden: "name";
    readonly riv: "name";
    readonly river: "name";
    readonly rvr: "name";
};
export declare const ssmStreetNameSubstitutions: {
    readonly allens: "Allen's";
    readonly andrews: "Andrew's";
    readonly ba: "Bay";
    readonly basils: "Basil's";
    readonly beac: "Beach";
    readonly bishops: "Bishop's";
    readonly c: "Chenes";
    readonly carmens: "Carmen's";
    readonly ch: "Chenes";
    readonly emmanu: "Emmanuel";
    readonly georges: "George's";
    readonly leighs: "Leigh's";
    readonly marys: "Mary's";
    readonly michaels: "Michael's";
    readonly p: "Park";
    readonly "people's": "Peoples";
    readonly "peoples'": "Peoples";
    readonly pk: "Park";
    readonly pleasan: "Pleasant";
    readonly point: "Pointe";
    readonly riv: "River";
    readonly rive: "River";
    readonly rvr: "River";
};
